feat: Use any embedding model with ragas
superlinear-ai/raglite pull request #56
Opened 2024-12-04 16:22 UTC by undo76

Use the configured embedder with Ragas

2024-12-04 16:45 UTC, lsorber requested changes
Only minor comments.

2024-12-04 16:51 UTC, lsorber commented
Unrelated to the review, but would you mind if we turn this into a `fix:`? You could argue RAGLite should have supported any embedding model to begin with. Also, I don't want to race minor version number bumps if we can avoid it.

2024-12-04 16:52 UTC, undo76 commented on src/raglite/_eval.py
> +    embedder = RAGLiteRagasEmbeddings(config=config)
It is just delegating to the RagLite embedder, but it would be nice to double check.

2024-12-04 17:04 UTC, undo76 commented on src/raglite/_eval.py
> +            return embeddings[0].tolist()  # type: ignore[no-any-return]
```
src/raglite/_eval.py: note: In function "evaluate":
src/raglite/_eval.py:234:13: error: Returning Any from function declared to
return "list[float]"  [no-any-return]
                return embeddings[0].tolist()
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2024-12-04 17:06 UTC, undo76 commented on src/raglite/_eval.py
> +            return embeddings[0].tolist()  # type: ignore[no-any-return]
This is declared like that, so it infers Any:
```
FloatMatrix = np.ndarray[tuple[int, int], np.dtype[np.floating[Any]]]
FloatVector = np.ndarray[tuple[int], np.dtype[np.floating[Any]]]
IntVector = np.ndarray[tuple[int], np.dtype[np.intp]]
```

2024-12-05 10:57 UTC, lsorber commented on src/raglite/_eval.py
> +            return embeddings[0].tolist()  # type: ignore[no-any-return]
I didn't mean to imply that this should be changed, it was just an observation. I checked and Ragas does indeed expect a list of Python floats as the return type [1], so this is fine!

[1] https://docs.ragas.io/en/stable/references/embeddings/#ragas.embeddings.BaseRagasEmbeddings

2024-12-05 10:58 UTC, lsorber approved these changes
I think this can be merged! But before we do, could you quickly confirm you tested this locally?

2024-12-05 12:42 UTC, undo76 commented
yes, it was tested and Ragas working with OpenAI as embedder.

2024-12-05 14:27 UTC, merged